/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.jtwitterstats;

import com.mongodb.client.MongoCollection;
import org.bson.Document;

/**
 *
 * @author JUANM
 */
public class Estadisticas extends javax.swing.JFrame {

    private Mongo m;
    private MongoCollection<Document> col;
    /** Creates new form Estadisticas */
    public Estadisticas(Mongo m) {
        initComponents();
        this.m = m;
        this.col = m.getCol();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palabrasclaves = new javax.swing.JButton();
        tweetsalmacenados = new javax.swing.JButton();
        Fecha = new javax.swing.JButton();
        retwitteado = new javax.swing.JButton();
        usuariotweets = new javax.swing.JButton();
        Minuto = new javax.swing.JButton();
        URLs = new javax.swing.JButton();
        Hashtags = new javax.swing.JButton();
        usuariosmencionados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        palabrasclaves.setText("Palabras claves");
        palabrasclaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabrasclavesActionPerformed(evt);
            }
        });

        tweetsalmacenados.setText("Número de tweets almacenados");
        tweetsalmacenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetsalmacenadosActionPerformed(evt);
            }
        });

        Fecha.setText("Fecha del primer y del último tweet");
        Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActionPerformed(evt);
            }
        });

        retwitteado.setText("Tweet más retwitteado");
        retwitteado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retwitteadoActionPerformed(evt);
            }
        });

        usuariotweets.setText("Usuario que con más tweets");
        usuariotweets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariotweetsActionPerformed(evt);
            }
        });

        Minuto.setText("Minuto más \"caliente\"");
        Minuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutoActionPerformed(evt);
            }
        });

        URLs.setText("URLs que aparecen más veces en los tweets");
        URLs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLsActionPerformed(evt);
            }
        });

        Hashtags.setText("Hashtags más frecuentes");
        Hashtags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HashtagsActionPerformed(evt);
            }
        });

        usuariosmencionados.setText("Los usuarios más mencionados");
        usuariosmencionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosmencionadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fecha)
                                .addGap(18, 18, 18)
                                .addComponent(URLs))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(palabrasclaves)
                                .addGap(33, 33, 33)
                                .addComponent(tweetsalmacenados)
                                .addGap(56, 56, 56)
                                .addComponent(Hashtags))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Minuto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(retwitteado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuariotweets)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuariosmencionados)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabrasclaves)
                    .addComponent(tweetsalmacenados)
                    .addComponent(Hashtags))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fecha)
                    .addComponent(URLs))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retwitteado)
                    .addComponent(usuariotweets)
                    .addComponent(usuariosmencionados))
                .addGap(29, 29, 29)
                .addComponent(Minuto)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palabrasclavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabrasclavesActionPerformed
        // TODO add your handling code here:
        m.palabrasclave(col);
    }//GEN-LAST:event_palabrasclavesActionPerformed

    private void tweetsalmacenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetsalmacenadosActionPerformed
        // TODO add your handling code here:
        m.tweetsalmacenados(col);
    }//GEN-LAST:event_tweetsalmacenadosActionPerformed

    private void HashtagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HashtagsActionPerformed
        // TODO add your handling code here:
        m.hashtags(col);
    }//GEN-LAST:event_HashtagsActionPerformed

    private void FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActionPerformed
        // TODO add your handling code here:
        m.fechaprimeryultimo(col);
    }//GEN-LAST:event_FechaActionPerformed

    private void URLsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLsActionPerformed
        // TODO add your handling code here:
        m.urls(col);
    }//GEN-LAST:event_URLsActionPerformed

    private void retwitteadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retwitteadoActionPerformed
        // TODO add your handling code here:
        m.masretwitteado(col);
    }//GEN-LAST:event_retwitteadoActionPerformed

    private void usuariotweetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariotweetsActionPerformed
        // TODO add your handling code here:
        m.usuariomastweets(col);
    }//GEN-LAST:event_usuariotweetsActionPerformed

    private void usuariosmencionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosmencionadosActionPerformed
        // TODO add your handling code here:
        m.usuariosmasmencionados(col);
    }//GEN-LAST:event_usuariosmencionadosActionPerformed

    private void MinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutoActionPerformed
        // TODO add your handling code here:
        m.minutocaliente(col);
    }//GEN-LAST:event_MinutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fecha;
    private javax.swing.JButton Hashtags;
    private javax.swing.JButton Minuto;
    private javax.swing.JButton URLs;
    private javax.swing.JButton palabrasclaves;
    private javax.swing.JButton retwitteado;
    private javax.swing.JButton tweetsalmacenados;
    private javax.swing.JButton usuariosmencionados;
    private javax.swing.JButton usuariotweets;
    // End of variables declaration//GEN-END:variables

}
